version: '2'

services:
  shield:
    image: starkandwayne/shield
    command: "start starkandwayne/shield --peer database --bind database:postgresql.shield"
    links:
    - database
  agent:
    image: starkandwayne/shield-agent
    environment:
      HAB_SHIELD_AGENT: |
        install_pg_tools=true
        shield_endpoint="https://shield"
        provisioning_key="autoprovision"
    command: "start starkandwayne/shield-agent --peer shield"
    links:
    - shield
  database:
    image: starkandwayne/postgresql
    command: "start starkandwayne/postgresql --group shield"
  target:
    image: starkandwayne/postgresql
    environment:
      HAB_POSTGRESQL: |
        [superuser]
        name = 'admin'
        password = 'admin'
    ports:
    - 5432:5432
    command: "start starkandwayne/postgresql --group target"
